import Head from "next/head";
import { useEffect } from "react";
import ArrowRight from "../components/svgs/ArrowRight";
import HeroIllustration from "../components/svgs/HeroIllustration";
import SearchIcon from "../components/svgs/SearchIcon";
// import Image from "next/image";

export default function Home() {
  useEffect(() => {
    document.body.classList.add("no-overflow");
    return () => {
      document.body.classList.remove("no-overflow");
    };
  }, []);

  return (
    <>
      <Head>
        <title>Progetto GC - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="home">
        <h1>LE MIGLIORI</h1>
        <h1>TRADUZIONI DEI </h1>
        <h1>TUOI TESTI PREFERITI</h1>
        <p>
          Inserire qui un testo carino riguardo il fatto che le nostre
          traduzioni sono migliori per motivo X.
        </p>
        <form action="submit">
          <input
            type="text"
            placeholder="Cerca qualcosa (canzoni, artisti, album)"
          />
          <button type="submit">
            <SearchIcon color="white" />
          </button>
        </form>
        <a href="#">
          Oppure dai un&apos;occhiata a tutte le nostre traduzioni{" "}
          <ArrowRight />
        </a>
        <div className="hero-illustration">
          <HeroIllustration />
        </div>
      </section>
    </>
  );
}
